#import "find_factors.h"

/********************************************************************
*   Works on small, valid large numbers generated by two primes.    *
********************************************************************/

int main(int argc, const char * argv[]) {
    
    @autoreleasepool {
        NSDate *startTime = [NSDate date];
        long long n = 1034776851837418228051242693253376923;
        int *p_array = (int *) malloc(sizeof(int)*n);
        if(p_array == NULL) {
            printf("malloc of size %d failed!\n", n);
            exit(1);
        }
        int array_size = 0;
        int floor_limit = 3;
        int upper_limit = n/2;

        
        // Remove evens, 1, 2
        for(int i=floor_limit; i <= upper_limit; i += 2) {
            if (n % i == 0){
                // check for primes
                int y=floor_limit;
                do {
                    if (i != y && i % y == 0){
                        printf("[+]Found a non-prime: %d\n",i);
                    }
 
                    y += 2;
                    
                }while( y < i );
                
                p_array[array_size] = i;
                array_size++;
            }
        }

        // Print results
        for(int i=0; i < array_size; i++)
            printf("[+]Found: %d\n",p_array[i]);

        free(p_array);

        printf("[+]time to finish: %f\n", -[startTime timeIntervalSinceNow]);
    }
    return 0;
}


//
//        YDFindFactors *find_factor = [[YDFindFactors alloc] init];
//        printf("[+]Factorize %d\n", find_factor.n);
//
//        printf("[+]Main thread, put a wait until thread finished\n");
//        for(int i = 1; i <= 10; i++) {
//                usleep(1000000);
//            }



//[[NSNotificationCenter defaultCenter] addObserverForName:@"Factorization" object:nil queue:nil usingBlock:^(NSNotification *note)
// {
//     NSLog(@"The action I was waiting for is complete!!!");
// }];
//
//[[NSNotificationCenter defaultCenter] postNotificationName:@"Factorization" object:nil userInfo:nil];
//
//[[NSNotificationCenter defaultCenter] removeObserver: @"Factorization"];
