#import "YDfind_factors.h"
#import "YDnotifications.h"

/********************************************************************
*   Works on small, valid large numbers generated by two primes.    *
********************************************************************/


int main(int argc, const char * argv[]) {
    
    @autoreleasepool {
        NSDate *startTime = [NSDate date];
        
        YDFindFactors *find = [[YDFindFactors alloc] init];

        [[NSNotificationCenter defaultCenter] addObserverForName:@"FactorSearchComplete" object:nil queue:nil usingBlock:^(NSNotification *note)
        {
            [YDNotifications receiveNotification:note];
            printf("[+]time to finish: %f\n", -[startTime timeIntervalSinceNow]);
        }];

        [[NSRunLoop currentRunLoop] run];
        
    }
    return 0;
}
